name: bot


on:
  workflow_dispatch:
    inputs:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test python
      run: |
        git clone https://github.com/yash-dk/TorToolkit-Telegram.git
        sudo cat << EOF >> TorToolkit-Telegram/tortoolkit/consts/ExecVarsSample.py
        ${{ secrets.BOT_CONF }}
        EOF
        sudo apt update
        sudo apt install -y python3.8
        sudo apt install -y python3-venv
        sudo apt-get install python3-setuptools
        python3 -m venv venv
        source venv/bin/activate
        cd TorToolkit-Telegram
        sudo pip3 install -r requirements.txt
        sudo apt install -y postgresql postgresql-contrib
        sudo apt -qq install -y curl git wget python3 python3-pip aria2 ffmpeg mediainfo unzip p7zip-full p7zip-rar
        curl https://rclone.org/install.sh | sudo bash
        sudo apt-get install -y software-properties-common
        sudo apt-get -y update
        sudo add-apt-repository -y ppa:qbittorrent-team/qbittorrent-stable
        sudo apt install -y qbittorrent-nox
        sudo systemctl --global start postgresql
        sudo -u postgres bash
        sudo createdb tortk
        sudo psql
        sudo ALTER USER postgres with password 'testpass';
        exit
        exit
        sudo export PORT=5432
        sudo chmod 777 start.sh
        sudo apt install nodejs
        sudo ./start.sh & sudo npx localtunnel --port 5432 --subdomain testbot237
