name: Jellyfinconfig

on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: JellyfinServer
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Jellyfin Install
        run: |
          sudo add-apt-repository ppa:qbittorrent-team/qbittorrent-stable
          sudo apt install qbittorrent-nox
          sudo adduser --system --group qbittorrent-nox
          sudo adduser runner qbittorrent-nox
          sudo apt install apt-transport-https
          sudo add-apt-repository universe
          wget -O - https://repo.jellyfin.org/ubuntu/jellyfin_team.gpg.key | sudo apt-key add -
          echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/ubuntu $( lsb_release -c -s ) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list
          sudo apt update
          sudo apt install jellyfin
          sudo chmod -R 755 /home/runner/
          sudo systemctl restart jellyfin
          sudo apt install nodejs
          sudo qbittorrent-nox --daemon --webui-port=8081
          timeout 5m npx localtunnel --port 8096 --subdomain jellyfintest || ( [[ $? -eq 124 ]] && \echo "WARNING: Timeout reached for jellyfin, but that's OK" ) & timeout 4m npx localtunnel --port 8081 --subdomain torrenttestgithub || ( [[ $? -eq 124 ]] && \echo "WARNING: Timeout reached for tor, but that's OK" )
          echo "Command Runs !" 
          sudo systemctl stop jellyfin
          sudo cp -R /var/lib/jellyfin /home/jellyfin
          cd /home/
          sudo zip -r jellyfinconfig.zip jellyfin
          sudo curl https://bashupload.com/jellyfinconfig.zip --data-binary @/home/jellyfinconfig.zip
          echo "suceessful !"
