name: olaris
on:
  schedule:
    - cron: '0 */6 * * *'
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: Olaris
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: rclone Install
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
      - name: rclone Config
        run: |
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONFIG }}
          EOF
      - name: Olaris Install
        run: |
          wget https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.deb
          sudo dpkg -i cloudflared-stable-linux-amd64.deb
          wget https://storage.googleapis.com/bysh-chef-files/olaris-release/olaris-linux-amd64-v0.3.3.zip
          sudo unzip olaris-linux-amd64-v0.3.3.zip -d /opt/olaris
          mkdir -p ~/.config/olaris
          cat >  ~/.config/olaris/olaris.toml  << EOF
          ${{ secrets.OLARIS }}
          EOF
          cd /opt/olaris/bin/
          sudo chmod +x olaris
          ./olaris > output.txt & cloudflared tunnel --url localhost:8080
