name: olaris
on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: Olaris
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Olaris Install
        run: |
          ls ~/.config/systemd/
