name: shellbot


on:
  workflow_dispatch:
    inputs:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: shell bot
      run: |
        sudo apt install -y make python build-essential
        sudo sh <(wget -qO- https://git.io/gclone.sh)
        git clone https://github.com/botgram/shell-bot.git && cd shell-bot
        mv config.example.json config.json
        cat >  config.json  << EOF
        ${{ secrets.SHELLBOT_CONFIG }}
        EOF
        npm install
        node server
