name: rdp


on:
  workflow_dispatch:
    inputs:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test python
      run: |
        sudo apt update
        sudo apt install apache2
        sudo systemctl restart apache2
        sudo apt install libapache2-mod-php7.2
        sudo apt install php7.2-curl php7.2-gd php7.2-zip
        sudo ufw allow 80
        sudo cat << EOF >> /var/www/html/info.php
        <?php
        phpinfo();
        ?>
        EOF
        dig +short myip.opendns.com @resolver1.opendns.com
        sudo apt install nodejs
        npx localtunnel --port 3389 
