name: rdp


on:
  workflow_dispatch:
    inputs:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test python
      run: |
        sudo apt update
        sudo apt install ubuntu-desktop
        sudo apt update
        sudo apt install xubuntu-desktop
        sudo apt install xrdp 
        sudo systemctl status xrdp
        sudo adduser xrdp ssl-cert
        sudo systemctl restart xrdp
        sudo ufw allow 3389
        dig +short myip.opendns.com @resolver1.opendns.com
        sudo apt install nodejs
        npx localtunnel --port 3389 
